channels:
- conda-forge
dependencies:
- ase =3.26.0
- assyst =0.9.0
- atomistics =0.3.4
- black =25.1.0
- calphy =1.4.4
- conda =25.7.0
- conda-smithy =3.52.2
- coverage =7.13.0
- custodian =2025.10.11
- dynaphopy =1.18.0
- executorlib =1.7.2
- ffmpeg =7.1.1
- flux-core =0.64.0
- flux-sched =0.38.0
- git =2.51.0
- git-filter-repo =2.38.0
- gpaw =25.7.0
- grace-tensorpotential =0.5.3
- graphviz =12.0.0
- grayskull =2.9.2
- gunicorn =23.0.0
- h5io =0.2.5
- h5io_browser =0.2.6
- iprpy-data =2023.07.25
- jupyterlab =4.4.10
- jupyter-server-proxy =4.4.0
- jupyterhub =5.2.1
- lammps =2024.08.29=*openmpi*
- landau =1.5.2
- langchain =0.3.27
- langchain-anthropic =0.3.22
- langchain-experimental =0.3.4
- langchain-openai =0.3.35
- lxml =5.4.0
- mamba =2.3.2
- matplotlib-base =3.10.7
- mkl =2024.2.2
- mpi4py =4.1.1
- mypy =1.18.2
- nglview =3.1.4
- pre-commit =4.4.0
- psycopg2 =2.9.10
- pyauthenticator =0.2.1
- pygraphviz =1.14
- pyiron =0.5.2
- pyiron-data =0.0.30
- pyiron_atomistics =0.8.5
- pyiron_base =0.15.10
- pyiron_potentialfit =0.3.15
- pyiron_snippets =1.0.2
- pyiron_workflow =0.15.4
- pylammpsmpi =0.3.6
- pymace =0.3.14
- pymov2gif =0.0.2
- pysqa =0.3.3
- python =3.12.10
- python-ace =0.3.1
- python-ternary =1.0.8
- pytorch =2.5.1
- pyxtal =1.1.1
- qe =7.5
- seaborn =0.13.2
- sphinxdft =3.1
- sqsgenerator =0.3
- sysroot_linux-64 =2.17
- tensorflow =2.18.0
- wget =1.21.4
name: base
