name: Pipeline

on:
  pull_request:

env:
  CONDA_OVERRIDE_ARCHSPEC: "x86_64"

jobs:
  pip_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: convert
      shell: bash -l {0}
      run: |
        ./.ci_support/convert_linux.sh
        cat environment.yml
        echo -e "channels:\n  - conda-forge\n" > .condarc
    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: "3.12"
        miniforge-version: latest
        condarc-file: .condarc
        environment-file: environment.yml
    - name: Test
      shell: bash -l {0}
      timeout-minutes: 30
      run: |
        pip install ./.ci_support --no-deps --no-build-isolation
        pip check

  linux_x64_test_environment:
    needs: [pip_check]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: convert
      shell: bash -l {0}
      run: |
        ./.ci_support/convert_linux.sh
        cat environment.yml
        echo -e "channels:\n  - conda-forge\n" > .condarc
    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: "3.12"
        miniforge-version: latest
        condarc-file: .condarc
        environment-file: environment.yml

  linux_x64_build_environment:
    needs: [linux_x64_test_environment]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Conda config
      run: echo -e "channels:\n  - conda-forge\n" > .condarc
    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: "3.12"
        miniforge-version: latest
        condarc-file: .condarc
        environment-file: .ci_support/environment.yml
    - name: Test
      shell: bash -l {0}
      timeout-minutes: 30
      run: |
        ./.ci_support/convert_linux.sh
        cat environment.yml
        python .ci_support/dryrun.py environment.yml env-linux-x64.yml 
    - uses: actions/upload-artifact@v4
      with:
        name: env-linux-x64.yml
        path: env-linux-x64.yml

  jupyter_docker_build_environment:
    needs: [pip_check]
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +%F)"
    - uses: actions/checkout@v4
    - name: Build pyiron/mpie_cmti
      timeout-minutes: 15
      run: |
        docker build -t pyiron/mpie_cmti:latest .
    - run: docker images
    - run: mkdir -p environment; chmod 777 environment
    - run: docker run -v $(pwd)/environment:/home/jovyan/ --rm pyiron/mpie_cmti /bin/bash -c 'source /opt/conda/bin/activate; conda env export > /home/jovyan/env-jupyter-docker-$(date +F).yml;'
    - name: test pyiron/cmti
      run: |
        docker run -v $(pwd)/test:/home/jovyan/test --rm pyiron/mpie_cmti /bin/bash -c 'source /opt/conda/bin/activate; python test/import.py;'
    - uses: actions/upload-artifact@v4
      with:
        name: env-jupyter-docker.yml
        path: environment/env-jupyter-docker-${{ steps.date.outputs.date }}.yml

  autobot:
    needs: [linux_x64_build_environment,jupyter_docker_build_environment]
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v4
      - name: Ignore broken packages
        shell: bash -l {0}
        run: python .ci_support/checktitle.py "${{ github.event.pull_request.title }}"
      - name: Enable auto-merge for bot PRs
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
